### ISSUE TITLE
Klok implementeren

### ISSUE THREAD

**Issue by rmens** [rmens/kabelkrant#1]
To do

**Comment by marijnvdwerf** [comment]
Misschien handing om `.top__datetime` een `text-align: right` mee te geven als het aan de rechterkant van het scherm hoort te staan

**Comment by rmens** [comment]
Dat is nu statisch, maar hoort de datum en tijd te zijn. Zo zag het eruit. Stond ook niet helemaal rechts.

![schermafbeelding 2016-11-28 om 22 53 06](https://cloud.githubusercontent.com/assets/6742496/20728118/91d5393a-b67c-11e6-91b6-e81ed7196df6.png)

**Comment by rmens** [comment]
Heb dit proberen te implementeren: http://www.webestools.com/scripts_tutorials-code-source-7-display-date-and-time-in-javascript-real-time-clock-javascript-date-time.html

**Comment by rmens** [comment]
Never mind. Zelf gedaan.
