### ISSUE TITLE
Logo's terug

### ISSUE THREAD

**Issue by rmens** [rmens/kabelkrant#3]
To do

**Comment by rmens** [comment]
Logo's zijn terug. @marijnvdwerf, wil jij mij dirty css eens checken? Misschien kan het efficiënter.

**Comment by marijnvdwerf** [comment]
Worden de logo's niet overlapt door de balk die erna komt?

**Comment by rmens** [comment]
Misschien beginnersgeluk, maar het ziet er precies zo uit als ik het wil hebben ;p 

![schermafbeelding 2016-11-29 om 21 39 18](https://cloud.githubusercontent.com/assets/6742496/20728069/586a16d4-b67c-11e6-9cf7-692f19ae752d.png)

**Comment by rmens** [comment]
Bij geen tegenbericht ga ik er maar vanuit dat dit OK is.
